### ISSUE TITLE
Catch and redirect on a 404 JS error

### ISSUE THREAD

**Issue by pld** [onaio/kpi#6]
If you go to a formbuilder URL you don't have cookies set, or you do not have access, you see an infinite loading circle, but the JS throws a 404 error.

<img width="1280" alt="screen shot 2017-01-03 at 12 27 02 pm" src="https://cloud.githubusercontent.com/assets/50706/21616604/11e9bc10-d1b0-11e6-8daa-aa0239caecbe.png">

We should catch the 404:

* If the cookies are not set, redirect the user to zebra login with an after login redirect back to this page
* If the cookies are set we redirect to the project on zebra (and they'll get a permission error there)
  * For this we'll need the user name and the project ID, then we redirect to [protocol]://[zebra-host]/[username]/[project id], and zebra can take it from there

**Comment by pld** [comment]
updated the description

**Comment by ivermac** [comment]
<img width="881" alt="screen shot 2017-01-04 at 10 59 13" src="https://cloud.githubusercontent.com/assets/1128227/21644513/d391f76c-d29e-11e6-8475-534aaf753785.png">
@pld So after further investigation, the 404 with `{"details": "not found"}` response actually doesn’t come from Ona API but from KPI's API as seen on the screenshot. So we neither have the `username` nor the `project id`. We'll need to find another way to solve this permission issue. May be render our own custom page notifying the user that he/she doesn't have permissions to the form.

**Comment by ivermac** [comment]
@pld I researched on this and I haven't really been successful because:
- they use flux architecture which has taken time and effort to understand and even to start playing with.
- In my opinion, the ideal place to add the view would be after [this line](https://github.com/kobotoolbox/kpi/blob/master/jsapp/js/editorMixins/editableForm.es6#L691) and it would be something like the following:
```javascript
if (<condition-if-user-does-not-have-permission-to-asset>) {
      return (
          <DocumentTitle title='Permission Denied'>
            <h1>You dont have permissions to this form</h1>
          </DocumentTitle>
      )
    }
```
but I noticed when I add a debugger or console.log, that section is called multiple times depending on whether that user has permission to the asset or not. This makes it hard to know if the call to retrieve an asset was successful or not.

Someone else might as well look at the code and play around with it a bit.

**Comment by pld** [comment]
Is there a way to extract username and project ID?

**Comment by ivermac** [comment]
I don't know the best way to answer your question but i'll give it a try. 
**Challenge 1**
One of the things I added on KPI when saving an asset was to add a project id so that it is deployed to the project it was launched from. The asset endpoint - `http://<formbuilder-url>/assets/<asset-unique-id>` - requires both authentication credentials and permissions to get a valid json response which contains the project id, meaning, a user with invalid credentials or without permissions to the asset cannot retrieve the asset. Also, I don't know if there is another endpoint that allows a user without credentials to retrieve an asset. 
**Challenge 2**
If we were to add an endpoint which when provided an unique-asset-id it then returns  a project id, we will need to make an extra api call to core to retrieve the owner (username) of the project and this call will require valid credentials, which at this point we don't have because KPI already complained this user doesn't have permissions to the asset.
**Challenge 3**
Even if we were able to retrieve the project id and the username, the function in [this line](https://github.com/onaio/kpi/blob/onaio/jsapp/js/actions.es6#L648) is called after the view (see screenshot below), in [this line](https://github.com/onaio/kpi/blob/onaio/jsapp/js/editorMixins/editableForm.es6#L703) has already been rendered. It's flux which I haven't figured how well it works
<img width="1279" alt="screen shot 2017-01-06 at 17 58 09" src="https://cloud.githubusercontent.com/assets/1128227/21721413/58d1725e-d439-11e6-9658-503ff6080f99.png">

**Comment by pld** [comment]
@ivermac I think you found the best way 😄 

This isn't a blocker to release. How much work would it be to change it so that when you hit the formbuilder the project owner name and project ID are stored in a way such that whomever accesses that asset can retrieve them without any authentication?

**Comment by ivermac** [comment]
I don't how much work it would involve, it would require changes both on client and server side. I'll have to check the source code

**UPDATE**: both zebra/core and formbuilder have their own permissions i.e If user `A` creates a project `B` and shares it with user `C`, user `C` will have permissions to project `B` and forms in it BUT won't have permissions to the formbuilder urls generated by user A using the formbuilder. That means the suggestion of redirecting a user - in this case user C - who has no permissions to a formbuilder url - in this case a url generated by user A - won't work for a user who already has permissions to the project where the formbuilder asset has already been deployed or yet to be deployed. The solution that @pld and I have agreed upon is that if we get an error response from the formbuilder server side, we will redirect the user to a generic page that will have:
1. Text saying the user has no permission(s) to that formbuiler url.
2. A link that redirects a user to zebra's login page.

**Comment by ivermac** [comment]
I'm closing this issue, I think we added this already. Re-open it if we haven't implemented it.
